export enum AT {
    CARS_SETTINGS_RESET = 'CARS_SETTINGS_RESET',
    CARS_SETTINGS_UPDATE = 'CARS_SETTINGS_UPDATE',
    SETTINGS_RESET = 'SETTINGS_RESET',
    SETTINGS_UPDATE = 'SETTINGS_UPDATE'
}

export default AT