export enum AT {
    CARS_RESET = 'CARS_RESET',
    CARS_TOGGLE_MOVEMENT = 'CARS_TOGGLE_MOVEMENT',
    CARS_SETTINGS_RESET = 'CARS_SETTINGS_RESET',
    CARS_SETTINGS_UPDATE = 'CARS_SETTINGS_UPDATE',
    PAILSRAILS_RESET = 'PAILSRAILS_RESET',
    PAILSRAILS_TOGGLE_MOVEMENT = 'PAILSRAILS_TOGGLE_MOVEMENT',
    SETTINGS_RESET = 'SETTINGS_RESET',
    SETTINGS_UPDATE = 'SETTINGS_UPDATE'
}

export default AT